config/routes.rb
NuestrosPrecios::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
    end
  end

  resources :companies
  resources :products
  resources :cities
  resources :countries

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/auth/:provider/callback', :to => 'sessions#create_omniauth'

  match '/api/users/new', :to => 'users#create_json'
  match '/api/login', :to => 'sessions#create_json'
  match '/api/list', :to => 'companies#getCompaniesWithProducts'

  root :to => 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  nickname        :string(255)
#  password        :string(255)
#  email           :string(255)
#  phone           :string(255)
#  birthday        :date
#  gender          :string(255)
#  city_id         :integer
#  user_type_id    :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :birthday, :city_id, :email, :gender, :name, :nickname,
  :password, :phone, :user_type_id, :password_confirmation, :user_type, :city

  attr_accessor :skip_password_validation

  has_many :authorizations
  has_many :companies
  has_many :company_branches
  belongs_to :user_type
  belongs_to :city

	has_secure_password

  before_save { email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :nickname, uniqueness: { case_sensitive: false }
  validates :password, :presence => true, length: { minimum: 6 }, :unless => :skip_password_validation
  validates :password_confirmation, presence: true, :unless => :skip_password_validation

  def random_nick
    first_name = self.name.split(' ').first
    self.nickname = "#{first_name}#{(rand() * 100).to_i}"
  end

  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end

  def admin?
    if (self.user_type == UserType.find_by_name('admin')) && (self.user_type!= nil)
      return true
    else
      return false
    end
  end

  def register?
    if ((self.user_type == UserType.find_by_name('register')) ||
      (self.user_type == UserType.find_by_name('facebook')) ||
      (self.user_type == UserType.find_by_name('android'))) &&
      (self.user_type!= nil)
      return true
    else
      return false
    end
  end

  def custom_update_attributes(params)
    if params[:password].blank?
      params.delete :password
      params.delete :password_confirmation
      update_attributes params
    end
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/user_type.rb
# == Schema Information
#
# Table name: user_types
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class UserType < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      @user.random_nick
      @user.user_type = UserType.find_by_name("register")
      if @user.save
        # Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(@user).deliver

        sign_in @user
        format.html { redirect_to @user, notice: 'Usuario creado exitosamente.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_json
    @user = User.new(params[:user])
    @user.random_nick
    @user.user_type = UserType.find_by_name("android")
    if @user.save
      render json: @user
    else
      render json: @user.errors
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    params[:user][:city] = City.find(params[:user][:city])

    respond_to do |format|
      @user.skip_password_validation = true
      if @user.custom_update_attributes(params[:user])
        sign_in @user
        format.html { redirect_to @user, notice: 'Perfil actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def password
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user
        format.html { redirect_to @user, notice: 'Password actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "password" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.nickname) %>
<div id="reg_form" class="bg_form">
	<h1>Editar Perfil</h1>

	<div class="row">
    <div class="span6">
    	<%= form_for(@user) do |f| %>
    		<%= render 'error_messages' %>

				<%= f.label :nombre, :class => "label_form" %>
		    <%= f.text_field :name, :class => "text_field_form"  %>

		    <%= f.label :usuario, :class => "label_form" %>
		    <%= f.text_field :nickname, :class => "text_field_form"  %>

		    <%= f.label :email, :class => "label_form" %>
		    <%= f.text_field :email, :class => "text_field_form"  %>

		    <%= f.label :telefono, :class => "label_form" %>
		    <%= f.text_field :phone, :class => "text_field_form"  %>

		    <%= f.label :fecha_de_cumpleaños, :class => "label_form" %>
		    <%= f.datepicker :birthday, :class => "text_field_form"  %>

		    <%= f.label :sexo, :class => "label_form" %>
		    <%= f.select :gender, options_for_select(%w[Hombre Mujer]), options ={}, :class => "select_form"%>

		    <%= f.label :ciudad, :class => "label_form" %>
		    <% if (@user.city.nil?) %>
		    <%= f.collection_select :city, City.all, :id, :name, {:include_blank => 'Seleccione una ciudad'},:class => "select_form" %>
		    <% else %>
		    <%= f.collection_select :city, City.all, :id, :name, {:selected => @user.city.id},:class => "select_form" %>
		    <% end %>

		    <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
		  <% end %>
		  <hr>
			<p>
				<%= link_to 'Regresar', @user %> -
				<%= link_to 'Cambiar contraseña', password_user_path(@user) %>
			</p>
		</div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuarios') %>
<div id="reg_form" class="bg_form">
  <h1>Listado de usuarios registrados</h1>

  <% @users.each do |user| %>
    <hr>
    <div class="user">
        <p><%= user.name %></p>
        <p><%= user.nickname %></p>
        <p><%= user.email %></p>
        <p><%= user.phone %></p>
        <p><%= user.birthday %></p>
        <p><%= user.gender %></p>
        <% if (!user.city.nil?) %>
          <p><%= user.city.name %></p>
        <% end %>
        <p><%= user.user_type.name %></p>
        <p><%= link_to 'Mostrar', user %>
          <% if can? :update, user %>
          - <%= link_to 'Editar', edit_user_path(user) %>
          <% end %>
          <% if can? :destroy, user %>
          - <%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Estas seguro?' } %>
          <% end %>
        </p>
    </div>
  <% end %>
  <hr>
  <% if can? :create, User %>
    <%= link_to 'Nuevo usuario', new_user_path %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Registro') %>
<div id="reg_form" class="bg_form">
  <h1>Registrate</h1>

  <div class="row">
    <div class="span6">
      <%= form_for(@user) do |f| %>
        <%= render 'error_messages' %>

        <%= f.label :nombre, :class => "label_form" %>
        <%= f.text_field :name, :class => "text_field_form" %>

        <%= f.label :email, :class => "label_form" %>
        <%= f.text_field :email, :class => "text_field_form" %>

        <%= f.label :password, :class => "label_form" %>
        <%= f.password_field :password, :class => "text_field_form" %>

        <%= f.label :password_confirmation, "Confirmar password", :class => "label_form" %>
        <%= f.password_field :password_confirmation, :class => "text_field_form" %>

        <%= f.submit "Crear mi cuenta", class: "btn btn-primary btn_form" %>
        <hr>
         <p>¿Ya eres miembro? <%= link_to "Ingresa aqui!", signin_path %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/password.html.erb
<% provide(:title, @user.nickname) %>
<div id="reg_form" class="bg_form">
	<h1>Cambiar contraseña</h1>

	<div class="row">
    <div class="span6">
    	<%= form_for @user, :url => { :action => "update_password" } do |f| %>
    		<%= render 'error_messages' %>

		    <%= f.label :password, "Nueva contraseña", :class => "label_form" %>
        <%= f.password_field :password, :class => "text_field_form" %>

        <%= f.label :password_confirmation, "Confirmar contraseña", :class => "label_form" %>
        <%= f.password_field :password_confirmation, :class => "text_field_form" %>

		    <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
		  <% end %>
		  <hr>
			<%= link_to 'Regresar', @user %>
		</div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.nickname) %>
<div class="row">
  <div id="reg_form" class="bg_form">
    <p>
      <b>Nombre:</b>
      <%= @user.name %>
    </p>

    <p>
      <b>Usuario:</b>
      <%= @user.nickname %>
    </p>

    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>

    <p>
      <b>Telefono:</b>
      <%= @user.phone %>
    </p>

    <p>
      <b>Fecha de cumpleaños:</b>
      <%= @user.birthday %>
    </p>

    <p>
      <b>Sexo:</b>
      <%= @user.gender %>
    </p>

    <% if (!@user.city.nil?) %>
      <p>
        <b>Ciudad:</b>
        <%= @user.city.name %>
      </p>
    <% end %>

    <% if can? :update, @user %>
      <%= link_to 'Editar Perfil', edit_user_path(@user) %> |
    <% end %>
    <%= link_to 'Regresar', users_path %>
  </div>
</div>