config/routes.rb
NuestrosPrecios::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
    end
  end

  resources :companies
  resources :products
  resources :cities
  resources :countries

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/auth/:provider/callback', :to => 'sessions#create_omniauth'

  match '/api/users/new', :to => 'users#create_json'
  match '/api/login', :to => 'sessions#create_json'
  match '/api/list', :to => 'companies#getCompaniesWithProducts'

  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <p class="text-center">@Todos los derechos reservados - MovilBrains.net</p>
</div>

app/views/layouts/_menu_bar.html.erb
<div class="menu_bar gradient">
	<div id="copyrigth">
		<%= render 'layouts/footer' %>
	</div>
	<div>
		<%= image_tag("logo2.png", :alt => "NuestrosPrecios", :class => "btn_bar", :id => "btnBar") %>
	</div>
	<div id="dialog-confirm" title="Opciones" style="display: none">
		<% if signed_in? %>
	    <%= link_to "Mi perfil: "+current_user.name, current_user %>
	    <br>
	    <%= link_to "Salir", signout_path, method: "delete" %>
	  <% else %>
	    <%= link_to "Ingresar", signin_path %>
	    <br>
	    <%= link_to "Registrate", signup_path %>
	  <% end %>
	  <br>
	  <%= link_to "Empresas", companies_path %>
	  <br>
	  <%= link_to "Productos", products_path %>
	  <br>
	  <%= link_to "Ciudades", cities_path %>
	  <br>
	  <%= link_to "Inicio", root_path %>
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("logo3.png", :alt => "NuestrosPrecios" ),
root_path, :class => 'brand img_brand' %>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
 <div class="nav-collapse">
    <ul class="nav pull-right">
        <li class="dropdown" id="accountmenu">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= image_tag("user.png", :alt => "Usuarios") %>
            <% if signed_in? %>
                <span><%= current_user.name %></span>
            <% end %>
            <!-- <b class="caret"></b> -->
        </a>
        <ul class="dropdown-menu">
          <% if signed_in? %>
            <li><%= link_to "Mi perfil: "+current_user.name, current_user %></li>
            <li class="divider"></li>
            <li><%= link_to "Salir", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Ingresar", signin_path %></li>
            <!-- <li class="divider"></li> -->
            <li><%= link_to "Registrate", signup_path %></li>
          <% end %>
        </ul>
        </li>

      <li class="dropdown" id="accountmenu">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= image_tag("cog.png", :alt => "Opciones") %>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to "Ciudad", cities_path %></li>
            <li><%= link_to "Idioma", root_path %></li>
        </ul>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="">
    <meta name="author" content="MovilBrains">
    <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/smoothness/jquery-ui.css" %>
    <%= javascript_include_tag "application" %>
    <!--[if IE 9 ]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= render 'layouts/menu_bar' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>